### ISSUE TITLE
Refactoring for v2.0.0 (draft)

### ISSUE THREAD

**Issue by puzrin** [nodeca/mincer#150]
Current architecture is copied from ruby.

- Internals are  overengineered and difficult to understand.
- Speed also can be improved.
- Some things like source maps are integrated via kludges.

This ticket should collect suggestions on architecture changes, to make everything more simple.

UPD. hike was rewritten. It did not increased speed, but at least now i'm sure that it has no problems.

**Comment by puzrin** [comment]
Closing. We dropped mincer from nodeca. No need to keep endless tivkets.

**Comment by tortuetorche** [comment]
Hi @puzrin,

Is this project still have maintenance released ?
What are tools do you suggest to replace it ?

Cheers,
Tortue Torche

**Comment by puzrin** [comment]
> Is this project still have maintenance released?

I have no plans no spend noticeable time on it, but if someone will send PR, it will be updated. Also i can share permissions if someone wish to continue.

> What tools do you suggest to replace it?

I see no problems with continue use mincer if it satisfies your needs. And here is our new code if that helps to anyone: https://github.com/nodeca/nodeca.core/blob/master/lib/system/init/bundle.js.

**Comment by tortuetorche** [comment]
@puzrin :+1:

**Comment by tortuetorche** [comment]
And do you plan to extract [Bundler](https://github.com/nodeca/nodeca.core/tree/master/lib/bundler) from Nodeca, as a standalone package like Mincer?

**Comment by puzrin** [comment]
No. My experience shows that it takes a lot of time to generalize such things for good library. And my goal is to create nodeca ("product"), not libraries :) .

**Comment by tortuetorche** [comment]
Alright, maybe I'll try to extract it for a future project...

**Comment by puzrin** [comment]
No problem. Just note that code is a bit dirty. We usually polish after several months of use.

**Comment by tortuetorche** [comment]
I'm not hurried :smile_cat:

**Comment by aug-riedinger** [comment]
@puzrin by curiosity, what do you use in nodeca as an asset build tool?

Mincer seemed to me like a super powerful tool that no other library would rival with...

**Comment by puzrin** [comment]
@aug-riedinger see links above

**Comment by aug-riedinger** [comment]
Saw it, sorry to have bothered.

Would you mind explaining why you moved away from mincer instead of another custom solution?

**Comment by puzrin** [comment]
Mincer is too file-centric. We needed component-centric tool. Similar code but different approach.
