### ISSUE TITLE
Does not work with less 2.0

### ISSUE THREAD

**Issue by aziz** [nodeca/mincer#167]
It seems the problem is in the less_engine.js 

`mincer/lib/mincer/engines/less_engine.js:87:36`
`[LessEngine] Cannot set property 'asset_data_uri' of undefined`

**Comment by puzrin** [comment]
Examples are broken with 2.x

**Comment by puzrin** [comment]
@ixti we need ci tests for example server & manifest.

**Comment by puzrin** [comment]
False alert. Error was caused by twbs. After update no more problems
