### ISSUE TITLE
Sass/SCSS source map support 

### ISSUE THREAD

**Issue by tortuetorche** [nodeca/mincer#172]
Here the plan to achieve this goal:
* [ ] Borrowed the [less_engine.js](https://github.com/nodeca/mincer/blob/a506585aac2b6d78db8d10e323f2f37a4d803a04/lib/mincer/engines/less_engine.js#L114) source mapping stuff
* [ ] Used [node-sass](https://github.com/sass/node-sass/blob/d10f348e07f0b894d95b1fc9b3349fe7259301c4/test/api.js#L271) source map API
* [ ] Update the [sass_engine.js](https://github.com/nodeca/mincer/blob/c80c344d96cd59650293cb8c12f6c6db7c7605be/lib/mincer/engines/sass_engine.js#L68) file to add source map support

I'll try to do this in the next two months.

**Comment by steel** [comment]
+1

**Comment by percyhanna** [comment]
I have written a [Sass engine for Mincer](https://github.com/percyhanna/mincer-ruby-sass) that has several advantages:

* Uses the official Ruby Sass release
* Has source map support

Please feel free to check it out and provide any feedback!

**Comment by puzrin** [comment]
#208 in progress
