### ISSUE TITLE
Macros: path used in require() call?

### ISSUE THREAD

**Issue by at0g** [nodeca/mincer#178]
Hello,

I'm having issues with macros - I am trying to write the semver string from package.json in a helper (version) into a .styl file, but get a require error.

I am using `mincer 1.2.2`.

My project is organised like this:

```
- assets
  - css
    - styles.css.stylus
- app.js
- package.json
```

/app.js:

```
var environment = new Mincer.Environment();
environment.appendPath('assets/css');
environment.registerHelper('version', function () {
    return require(__dirname, '/package.json').version;
});

Mincer.logger.use(console);
Mincer.MacroProcessor.configure(['.css']);

app.use('/assets', Mincer.createServer(environment));
```

/assets/css/styles.css.styl:

```
body
  &:before
    content "'$$ version() $$'"
    display block
```

When requesting the assets/styles.css, I get the following error:

```
Served asset /assets/styles.css - 500 Error compiling asset: [MacroProcessor] Failed to evaluate macro `version()` [Cannot find module '/absolute/path/to/project/root'] (in /absolute/path/to/project/root/assets/css/styles.css.styl:5) (13ms)
```

If I change the version helper to return a static string instead of requiring package.json, then the error does not occur.

Any ideas?

**Comment by puzrin** [comment]
`require(path.join(...))`

You code should not work without macros too, pah.join missed.

**Comment by at0g** [comment]
Thanks - adding path.join works as expected. 

The version helper code was from the example in the mincer readme. 
Perhaps a correction is needed?
https://github.com/nodeca/mincer/pull/179
