### ISSUE TITLE
Less 2.x source maps is broken

### ISSUE THREAD

**Issue by tortuetorche** [nodeca/mincer#189]
`mincer` >= 1.2.2 breaks source mapping with `less` >=2.0.
With `less` 1.7.* it's OK.

I think we need to check in the [`less_engine.js`](https://github.com/nodeca/mincer/blob/d73d39974a7268d056987ee3d8383f63facb47cf/lib/mincer/engines/less_engine.js#L148) file if the code for `less` 2.* works with source maps.

**Comment by puzrin** [comment]
As far as i remember, Less 2.+ support was added by @tikotzky 

https://github.com/nodeca/mincer/pull/174

What do you means as "breaks source mapping" ? Crashes? Invalid mapping for less files part? Invalid mapping for everything?

**Comment by tortuetorche** [comment]
I'm unable to access the `less` source. When I precompile my assets I've no errors.

**Comment by tortuetorche** [comment]
I think it's a bug when the source maps for `less` files are generated.

**Comment by tortuetorche** [comment]
Maybe we need to pass some sourceMap options like  `sourceMapRootpath` and `sourceMapBasepath` [here](https://github.com/nodeca/mincer/blob/d73d39974a7268d056987ee3d8383f63facb47cf/lib/mincer/engines/less_engine.js#L154).

See Less 2 [doc](http://lesscss.org/usage/#programmatic-usage) for more informations.

**Comment by tortuetorche** [comment]
Here some news, I tried to add some of the `sourceMap` options I mentioned above in the `less.render()` and no luck :sob:

**Comment by puzrin** [comment]
@ixti, need fix. Mappings are ok, but embedded css bodies are missed in 2.0.
