### ISSUE TITLE
Mincer throws 'TypeError: Not a string or buffer'

### ISSUE THREAD

**Issue by yumitsu** [nodeca/mincer#192]
Good day. I encountered an error(?) with mincer compiling scss assets.
When you add an empty scss file and start recompiling the assets, mincer throws 'TypeError: Not a string or buffer'.

It's not that critical, but I wonder why this error occurs. In my opinion mincer should return empty string instead of exception.

**Comment by ixti** [comment]
Thanks for report!

**Comment by yumitsu** [comment]
@ixti Sorry, I forgot to mention versions: `node-sass: 2.1.1`, `libsass: 3.1.0`, `mincer: latest`, OS: OSX 10.9.5.

**Comment by puzrin** [comment]
Should be solved in latest release
