### ISSUE TITLE
Mincer.Server does not serve assets mapped from manifest

### ISSUE THREAD

**Issue by jeremyruppel** [nodeca/mincer#197]
Currently, if I compile my assets and pass the manifest to a server, the server will not serve assets by their logical path. Suppose I have the following manifest.json:

``` json
{
  "assets": {
    "client.js": "client-2035732ab934f021c62398af7983f4d6.js"
  },
  "files": {
    "client-2035732ab934f021c62398af7983f4d6.js": {
      "logical_path": "client.js",
      "mtime": "2015-05-28T00:03:31.000Z",
      "size": 15506,
      "digest": "2035732ab934f021c62398af7983f4d6"
    }
  }
}
```

I would expect to be able to do the following:

``` js
app.use('/assets', Mincer.createServer(environment.index, require('./manifest.json'));
// GET /assets/client.js serves /assets/client-2035732ab934f021c62398af7983f4d6.js
```

But after the server verifies the asset exists in the manifest, [it tries to `findAsset('client.js')` instead of `findAsset(this.manifest.assets['client.js'])`][1] and ends up serving client.js instead. I'd be happy to contribute a patch but I'm finding it difficult to write tests around this.

[1]: https://github.com/nodeca/mincer/blob/master/lib/mincer/server.js#L257-L263

**Comment by ixti** [comment]
`Mincer.createServer` uses manifest data only to avoid servings assets not listed in it. In other words manifest used as a white-list filter only.
