### ISSUE TITLE
Error: Can not find asset 'angular-bootstrap/bower.json'

### ISSUE THREAD

**Issue by jtblin** [nodeca/mincer#202]
Hi, I am getting the error `Can not find asset 'angular-bootstrap/bower.json'` when compiling ( i.e. `manifest.compile`) assets in directory pulled by `bower`.

In `Base.prototype.resolve`, I can see that mincer does find the bower.json which is 

```
{ author: { name: 'https://github.com/angular-ui/bootstrap/graphs/contributors' },
  name: 'angular-bootstrap',
  keywords: [ 'angular', 'angular-ui', 'bootstrap' ],
  license: 'MIT',
  ignore: [],
  description: 'Native AngularJS (Angular) directives for Bootstrap.',
  version: '0.13.0',
  main: [ './ui-bootstrap-tpls.js' ],
  dependencies: { angular: '>=1.3.0' } }
```

But the following code seems to expect that the extension for `bower.main` is empty or `.json` as the `bower.json` file.

```
      if (_.isArray(bower.main)) {
        extname = path.extname(logicalPath);

        _.forEach(bower.main, function (mainfile) {
          if (extname === '' || extname === path.extname(mainfile)) {
            return fn(path.join(path.dirname(pathname), mainfile));
          }
        });
      }
```

It'd be great if mincer could handle compiling assets pulled by bower as indicated in "main" in "bower.json".

**Comment by ixti** [comment]
Can you please provide an example, as I'm not quite uniderstand what exactly are you trying to achieve.

**Comment by jtblin** [comment]
I'm trying to compile the assets in directories:

```
var environment = new Mincer.Environment('./');

  environment.registerHelper('version', function() {
    return require(__dirname + './package.json').version;
  });

  environment.registerHelper('asset_path', function(name, opts) {
    var asset = environment.findAsset(name, opts);
    if (!asset){
      throw new Error("File [" + name + "] not found");
    }

    return mountPoint + '/' + asset.digestPath;
  });

  environment.jsCompressor = 'uglify';
  environment.cssCompressor = 'csso';

  [
    'assets/'
  ].forEach(function(path) {
      environment.appendPath(path);
    });

  [
    'assets/vendor'
  ].forEach(function(path) {
      environment.prependPath(path);
    });

  var manifest = new Mincer.Manifest(environment, './public/assets');

  console.info('Starting asset compilation');

  var manifestData = manifest.compile(['*', '*/**']);
```

But it chokes when it encounters a `bower.json` file. Ideally `mincer` would be smart enough to only compile the assets indicated in `bower.json` when there is one, but that's probably very complicated so at least it should not choke and just process everything like it used to do. That used to work until I upgraded `mincer` to `1.3`.

**Comment by ixti** [comment]
Hm. Well, it's kinda expected behavior.

When bower manifest is being processed it spits out "main" asset depending on context of current execution (e.g. when it require from JS asset, then we will use `.js` from main, for css - css). If you want to compile with manifest using wildcards specify extensions you care of then:

``` javascript
manifest.compile(['*', '**.js', '**.css', '**.png', ...]);
```

In any case compiling by wildcard sometimes lead to pretty unpredictable results.
I see what you want to achieve, but current code that handles bower is not capable of this.
If you will provide a PR - we can discuss it.
