### ISSUE TITLE
manifest.compile is not returning to console

### ISSUE THREAD

**Issue by lutzk** [nodeca/mincer#206]
it compiles properly

`Assets were successfully compiled.
Manifest data (a proper JSON) was written to:
/Users/.../dev/proj/public/assets/manifest.json`

all assets are realy there

this happend after i upgraded to 1.3.0
i followed example: https://github.com/nodeca/mincer/blob/master/examples/manifest.js
but after logging the files and the manifest it dont return to console

**Comment by ixti** [comment]
Just tried, all works as expected.
Will need more details (node version / npm version) and probably sandbox with all node_modueles installed so I could try same code you were running.

**Comment by lutzk** [comment]
than you for checking
i upgraded to 1.3.1 and coud not reproduce it anymore :)
