### ISSUE TITLE
Problem with tpl.js files

### ISSUE THREAD

**Issue by SimeonC** [nodeca/mincer#209]
Hey, I'm sure there's a simple fix for this but I can't find it. I'm trying to bundle up angular-strap with my other files and the tpl file is causing issues.

For this require directive `//= require resources/lib/angular-strap/dist/angular-strap.tpl.min`, the file is named `angular-strap.tpl.min.js` I get the following error:

```
Warning: [DirectiveProcessor] resources/lib/angular-strap/dist/angular-strap.tpl.min is 'application/vnd.groove-tool-template', not 'application/javascript'  (in /Users/xan/WebStormProjects/tcx-sci/temp/sci.js:13) Use --force to continue.
```

Not sure if this is a mincer or grunt-mincer issue but it seems to come from mincer, any help would be much appreciated.

**Comment by puzrin** [comment]
There are no such message in mincer.

**Comment by ixti** [comment]
Please, provide sandbox which I can use to reproduce this issue.
Error message does not helps to figure out what's wrong unfortunatey.

**Comment by puzrin** [comment]
Closing - no feedback, doesn't seems to be a mincer error.
