### ISSUE TITLE
Expose the prop method in the mincer instance

### ISSUE THREAD

**Issue by aug-riedinger** [nodeca/mincer#222]
In [this project](https://github.com/ssar/mincer-babel), mincer needs to be loaded simply to get access to:

`var prop = require('mincer/lib/mincer/common').prop;` ([line 3](https://github.com/ssar/mincer-babel/blob/master/index.js))

Would be convenient to being able to access it from the `mincer` instance immediately.

**Comment by puzrin** [comment]
That's just a simple helpers for internal needs. I don't think it's good idea to expose those to public.

**Comment by ixti** [comment]
Just like @puzrin said, it's an internal helper that provide syntax sugar to define property, so it's as simple as:

``` javascript
Object.defineProperty(obj, "someProp", { value: 123 });
```

**Comment by aug-riedinger** [comment]
Yep, that's what I did on my branch then.
But what if for some reason this method becomes extended, with additional behavior ? It might break everywhere `Object.defineProperty(obj, "someProp", { value: 123 });` is used instead.
