### ISSUE TITLE
Request - Support HTML files in directive processor

### ISSUE THREAD

**Issue by mike-suggitt** [nodeca/mincer#223]
It would be really nice to bundle HTML files in the same way that CSS and JS are. It only requires a small change to the regex and the inclusion of the HTML MIME type.

```
var HEADER_PATTERN = new RegExp(
    '^(?:\\s*' +
    '(' +
    '(?:\/[*](?:\\s*|.+?)*?[*]\/)' + '|' +
    '(?:###\n(?:\\s*|.+?)*?\n###)' + '|' +

    '(?:\<!--(?:\\s*|.+?)*?--\>)' + '|' + //Include HTML files

    '(?:\/\/.*\n?)+' + '|' +
    '(?:#.*\n?)+' +
    ')*' +
    ')*', 'm');
```

Then simply set the mime type and plugin the direective processor

```
Mincer.registerMimeType('text/html', '.html');
Mincer.registerPreProcessor('text/html', Mincer.DirectiveProcessor);
```

I'd welcome your thoughts.

**Comment by mike-suggitt** [comment]
Bump

**Comment by ixti** [comment]
I'm pretty fine with this. Discussion should be continued in https://github.com/nodeca/mincer/pull/235
