### ISSUE TITLE
Sass syntax

### ISSUE THREAD

**Issue by eth0lo** [nodeca/mincer#83]
Consider using ruby's sass interpreter instead of node-sass, since node-sass only support scss syntax 

https://github.com/andrew/node-sass/issues/58

**Comment by percyhanna** [comment]
I have written a [Sass engine for Mincer](https://github.com/percyhanna/mincer-ruby-sass) that has several advantages:

* Uses the official Ruby Sass release
* Has source map support
* Uses Mincer's `dependOn` interface for defining dependencies for compiled Sass assets

Please feel free to check it out and provide any feedback!
